# Generated by Django 3.2.3 on 2021-06-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='realtor_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
