# Generated by Django 3.2.3 on 2021-05-28 19:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('garage', models.IntegerField()),
                ('sqft', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=2)),
                ('listing_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('published', models.BooleanField(default=True)),
                ('main_image', models.ImageField(upload_to='images/%m/')),
                ('image_1', models.ImageField(upload_to='images/%m/')),
                ('image_2', models.ImageField(upload_to='images/%m/')),
                ('image_3', models.ImageField(upload_to='images/%m/')),
                ('image_4', models.ImageField(upload_to='images/%m/')),
                ('image_5', models.ImageField(upload_to='images/%m/')),
                ('image_6', models.ImageField(upload_to='images/%m/')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtors.realtor')),
            ],
        ),
    ]
