# Generated by Django 3.2.3 on 2021-05-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='images/%m/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='images/%m/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='images/%m/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='images/%m/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_5',
            field=models.ImageField(blank=True, upload_to='images/%m/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_6',
            field=models.ImageField(blank=True, upload_to='images/%m/'),
        ),
    ]
