# Generated by Django 3.2.3 on 2021-05-28 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
