# Generated by Django 3.2.3 on 2021-05-28 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_realtor_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='join_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
