# Generated by Django 3.2.3 on 2021-05-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_alter_realtor_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='image',
            field=models.ImageField(default=None, upload_to='realtors/%m/'),
        ),
    ]
